### ISSUE TITLE
Support rails5

### ISSUE THREAD

**Issue by sonots** [sonots/activerecord-refresh_connection#5]
With this commit  https://github.com/rails/rails/commit/d3c9d808e3e242155a44fd2a89ef272cfade8fe8#diff-31e798bb03e4140196a88e242f488880R44, it seems `ActiveRecord::ConnectionAdapters::ConnectionManagement` was removed, and ActiveRecord::QueryCache does `ActiveRecord::Base.clear_active_connections!` at https://github.com/rails/rails/commit/d3c9d808e3e242155a44fd2a89ef272cfade8fe8#diff-31e798bb03e4140196a88e242f488880R44

**Comment by sonots** [comment]
rake middleware on rails5

```
use Rack::Sendfile
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Sprockets::Rails::QuietAssets
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use WebConsole::Middleware
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
run Example::Application.route
```

As a comparison, rake middleware on rails4

```
use Rack::Sendfile
use ActionDispatch::Static
use Rack::Lock
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007f85c16160e0>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
run Example::Application.routes
```

**Comment by sonots** [comment]
Tried

```
    config.middleware.insert_after ActiveRecord::Migration::CheckPending,
      "ActiveRecord::ConnectionAdapters::RefreshConnectionManagement"
```

on rails5 branch. https://github.com/sonots/activerecord-refresh_connection/tree/rails5/example/example

Hmm, show processlist stills shows a connection even after ActiveRecord::Base.clear_all_connections! is called.

```
mysql> show processlist;
+------+------+-----------+---------------------------------+---------+------+-------+------------------+
| Id   | User | Host      | db                              | Command | Time | State | Info             |
+------+------+-----------+---------------------------------+---------+------+-------+------------------+
| 2366 | root | localhost | activerecord-refresh_connection | Sleep   |   10 |       | NULL             |
| 2367 | root | localhost | NULL                            | Query   |    0 | init  | show processlist |
+------+------+-----------+---------------------------------+---------+------+-------+------------------+
```

Also, I get following errors finally

```
[2016-07-08 12:59:16] ERROR ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.001 seconds); all pooled connections were in use
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in `block in wait_poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `loop'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `wait_poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:154:in `internal_poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:278:in `internal_poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `block in poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:158:in `synchronize'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:709:in `acquire_connection'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:501:in `checkout'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:875:in `retrieve_connection'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_handling.rb:91:in `connection'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/query_cache.rb:47:in `block in install_executor_hooks'
```

It seems I need to learn the new ActiveSupport::Executor, ActiveSupport::Reloader API, but there is no reference at it ...?

**Comment by sonots** [comment]
@kamipo Do you have any idea to do this http://blog.livedoor.jp/sonots/archives/38797925.html on rails5 era? ;-) 🙇  I am not supposed to support puma (multi-thread).

**Comment by kamipo** [comment]
This `ActiveRecord::Base.connection` retrieves a new connection.
https://github.com/rails/rails/blob/v5.0.0/activerecord/lib/active_record/query_cache.rb#L47

I think we have two choices.

* call `RefreshConnectionManagement` outside `ActionDispatch::Executor`

```diff
--- a/example/example/config/application.rb
+++ b/example/example/config/application.rb
@@ -11,7 +11,7 @@ module Example
     # Settings in config/environments/* take precedence over those specified here.
     # Application configuration should go into files in config/initializers
     # -- all .rb files in that directory are automatically loaded.
-    config.middleware.insert_after ActiveRecord::Migration::CheckPending,
+    config.middleware.insert_before ActionDispatch::Executor,
       "ActiveRecord::ConnectionAdapters::RefreshConnectionManagement"
   end
 end
```

* suppress `clear_active_connections!` for `ActiveRecord::QueryCache`

```diff
--- /dev/null
+++ b/example/example/config/initializers/suppress_clear_active_connections.rb
@@ -0,0 +1,7 @@
+module ActiveRecord
+  class QueryCache
+    def self.install_executor_hooks(executor = ActiveSupport::Executor)
+      executor.register_hook(self)
+    end
+  end
+end
```

**Comment by sonots** [comment]
@kamipo Thanks!, but I still get error at 2nd time access.

> call RefreshConnectionManagement outside ActionDispatch::Executor

```
[2016-07-08 12:59:16] ERROR ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.001 seconds); all pooled connections were in use
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in `block in wait_poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `loop'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `wait_poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:154:in `internal_poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:278:in `internal_poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `block in poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:158:in `synchronize'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:709:in `acquire_connection'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:501:in `checkout'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:875:in `retrieve_connection'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_handling.rb:91:in `connection'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/query_cache.rb:47:in `block in install_executor_hooks'
```

> suppress clear_active_connections! for ActiveRecord::QueryCache

```
[2016-07-10 11:57:26] ERROR ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.001 seconds); all pooled connections were i
n use
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in `block in wait_po
ll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `loop'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `wait_poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:154:in `internal_poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:278:in `internal_poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `block in poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:158:in `synchronize'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `poll'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:709:in `acquire_connecti
on'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:501:in `checkout'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:875:in `retrieve_connect
ion'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_handling.rb:91:in `connection'
        /Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/query_cache.rb:27:in `run'
```

In rails4, ActiveRecord::Base.connection newly created connections every time after calling `clear_all_connections!`, but in rails5, we get the above error after calling `clear_all_connections!`.

**Comment by kamipo** [comment]
Hmm... Looks like that `with_new_connections_blocked` (introduced at https://github.com/rails/rails/pull/14938) have a race condition. This method sometimes causes `@new_cons_enabled = false` then never toggled to true.

**Comment by sonots** [comment]
oh ...

**Comment by sonots** [comment]
Did not work well with webrick, but worked well with unicorn.

**Comment by sonots** [comment]
Webrick starts new thread for each request https://github.com/ruby/ruby/blob/a00ec4cf3a43b67c8a3166ae22d321089446cf98/lib/webrick/server.rb#L191
In Rails 5, application must be thread-safe. That was why.

**Comment by sonots** [comment]
@kamipo Thanks, anyway :-)

**Comment by kamipo** [comment]
Anytime 😊
